version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5431/gen_diagram_db
      - VITE_API_URL=http://10.11.0.28:8000
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    image: postgres
    environment:
      POSTGRES_DB: gen_diagram_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
